### PR TITLE
eth status

### LINKED ISSUE #175: Add cli status commands
## Summary of bug
 
One cannot tell if the status of the eth connection nor of plasmad
## Expected behavior

Easily figure out the current state of the eth connection (syncing, crashed etc) and of plasmad (current block num)

Add `status` commands to plasmacli, perferably `plasmacli eth status` and `plasmacli query status`

### PR DESCRIPTION
**Pull request by wesgraham**
Continuation of previous "eth status" PR (on new branch), fixes #175

### CODE REVIEW

**Review by hamdiallam — APPROVED** [review]

File: cmd/plasmacli/subcmd/eth/status.go [hunk 1]
```diff
@@ -38,7 +39,7 @@ var statuscmd = &cobra.Command {
 		if synced {
 			num, err := client.LatestBlockNum()
 			if err != nil {
-				return fmt.Errorf("synced with eth node: %s \n error retrieving latest block height of eth endpoint: %s\n", conf.EthNodeURL , err)
+				return fmt.Errorf("eth node is syncing: %s", conf.EthNodeURL)
```
Comment (colin-axner) [inline cmd/plasmacli/subcmd/eth/status.go:42]: rip, I meant for this change to be on line 46, the previous error message here was fine. The variable synced is either true or false, true if it is fully synced up or false if it still in catch up mode. Any crash would be reported by an earlier error. Also for future note, hit the "squash and merge" button when merging, it keep commit history more readable

Comment (wesgraham) [reply cmd/plasmacli/subcmd/eth/status.go:42]: Whoops haha. Is there a best way to resolve? Will also squash & merge in the future

Comment (colin-axner) [reply cmd/plasmacli/subcmd/eth/status.go:42]: open a new pr with the fix. Not sure if this has been done yet?
